version: 2
jobs:
  build:
    working_directory: ~/reviews
    docker:
      - image: circleci/node:12
      - image: postgres:11
   steps:
      - checkout
      # update npm
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      # download and cache dependencies
      - restore_cache:
          key:
            - dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  tests:
    docker:
      - image: circleci/node:12
      - image: postgres:11
    steps:
      - checkout
      - run:
          name: Seed
          command: npm run seed
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
