version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
        environment:
          NODE_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: testuser
      - image: postgres:11.3
        environment:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup postgresql user
          command: sudo -u postgres psql -p 5432 -c "create user testuser with password 'testpass';"
          command: sudo -u postgres psql -p 5432 -c "alter user testuser with superuser;"
          command: sudo -u postgres psql -p 5432 -c "create database testdb;"
          command: sudo -u postgres psql -p 5432 -c "grant all privileges on database testdb to testuser;"
      -run: npm run test
