version: 2.1
jobs:
  build:
    working_directory: ~/reviews
    docker:
      - image: circleci/node:12
      - image: postgres:11
   steps:
      - checkout
      # update npm
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      # download and cache dependencies
      - restore_cache:
          key:
            - dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      # seed database
      - run: npm run seed
      # run tests
      - run: npm run test
      
