version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.16.0-jessie
        environment:
          NODE_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: cj
      - image: postgres:11.3-alpine
        environment:
          POSTGRES_DB: airbnb_clone_reviews
          POSTGRES_USER: cj
    steps:
      - checkout
      # - run: npm install
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run seed
      - run: npm test
      # - run:
      #     name: Setup postgresql user
      #     command: sudo -u postgres psql -p 5432 -c "create user testuser with password 'testpass';"
      #     command: sudo -u postgres psql -p 5432 -c "alter user testuser with superuser;"
      #     command: sudo -u postgres psql -p 5432 -c "create database circle-test_test;"
      #     command: sudo -u postgres psql -p 5432 -c "grant all privileges on database circle-test_test to testuser;"
  # test:
  #   working_directory: ~/repo
  #   docker:
  #     - image: circleci/node:12
  #       environment:
  #         NODE_ENV: test
  #         PGHOST: 127.0.0.1
  #         PGUSER: testuser
  #     - image: postgres:11.3
  #       environment:
  #         POSTGRES_DB: testdb
  #         POSTGRES_USER: testuser
  #         POSTGRES_PASSWORD: testpass
  #   steps:
  #     - checkout
  #     - run: npm run test
